export const SET_SELECTED_MENU_ITEM = 'SET_SELECTED_MENU_ITEM';

export const FETCH_COMMENTS = 'FETCH_COMMENTS';
export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS';
export const FETCH_COMMENTS_FAILURE = 'FETCH_COMMENTS_FAILURE';
export const SEND_COMMENT = 'SEND_COMMENT';
export const SEND_COMMENT_SUCCESS = 'SEND_COMMENT_SUCCESS';
export const SEND_COMMENT_FAILURE = 'SEND_COMMENT_FAILURE';

export const SELECT_MESSAGE = 'SELECT_MESSAGE';
